name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish_build:
    name: 'Publish build'
    #needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
        
      - name: 'Set up JDK 11' #18?
        uses: actions/setup-java@v3.10.0

        with:
          java-version: 11 #18?
          distribution: 'zulu'
          #server-id: sonatype-nexus-snapshots
          #server-username: CI_DEPLOY_USERNAME
          #server-password: CI_DEPLOY_PASSWORD
          #cache: 'maven'
          
      - name: 'Set up requirements'
        run: |
          curl https://launchpad.net/sikuli/sikulix/2.0.5/+download/sikulixide-2.0.5.jar --output /usr/share/java/sikulixide-2.0.5.jar
          apt install jython
          
      - name: 'Build package'
        run: |
          jython scripts/build.py
          
      - name: 'Publish'
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        run: ./scripts/deploy_snapshot.sh #util
